name: Lint rmw_iceoryx
on:
  pull_request:

jobs:
  lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
          linter: [cpplint, uncrustify, xmllint, copyright]
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@master
    - uses: ros-tooling/action-ros-lint@master
      with:
        linter: ${{ matrix.linter }}
        package-name: |
            rmw_iceoryx_cpp
